### ISSUE TITLE
Res-net do not work!!

### ISSUE THREAD

**Issue by Siyeong-Lee** [titu1994/Image-Super-Resolution#12]
Hi. I was very impressed with your code.
It was very helpful.

But the Res-Net part does not work when trainning .
The following error message is displayed.
---------------------------------------------------------------------------------------------------------------------------------------------
ValueError: CudaNdarray_inplace_elemwise need same dimensions (or broadcastable dimension)
Apply node that caused the error: GpuIncSubtensor{Inc;::, ::, int64::int64, int64::int64}(GpuAlloc{memset_0=True}.0, GpuSubtensor{::, int64::int64, ::, ::}.0, Constant{0}, Constant{2}, Constant{0}, Constant{2})
Toposort index: 1085
Inputs types: [CudaNdarrayType(float32, 4D), CudaNdarrayType(float32, 4D), Scalar(int64), Scalar(int64), Scalar(int64), Scalar(int64)]
Inputs shapes: [(128, 64, 16, 512), (128, 2, 8, 256), (), (), (), ()]
Inputs strides: [(524288, 8192, 512, 1), (16384, 8192, 256, 1), (), (), (), ()]
Inputs values: ['not shown', 'not shown', 0, 2, 0, 2]
Outputs clients: [[GpuIncSubtensor{Inc;::, ::, int64::int64, int64::int64}(GpuIncSubtensor{Inc;::, ::, int64::int64, int64::int64}.0, GpuSubtensor{::, int64::int64, ::, ::}.0, Constant{0}, Constant{2}, Constant{1}, Constant{2})]]
---------------------------------------------------------------------------------------------------------------------------------------------

Is it due to insufficient memory?
I don't understand that....

p.s I have also changed "nb_residual = 14" to 3

**Comment by titu1994** [comment]
Use channels_first data format. This code is not working on channels_last data format

**Comment by Siyeong-Lee** [comment]
Thank you for your quick reply.

you mean "use Theano"? right?
I am now running keras using theano.
and The basic model and  Deep denoising Network is learning normally.
 
but in Res-Net and GAN model,  do not working
though input, output scales are same..........

**Comment by titu1994** [comment]
You can change the day format without changing backend, it will still work, albeit train much slower. 

Also, he's the models aren't training well. I don't have much time to focus on this project these days, but if I do get time, I will try to improve the models. 

Sorry about that.

**Comment by Siyeong-Lee** [comment]
Thanks a lot !!!!!!!
