### ISSUE TITLE
Issue while training the Network

### ISSUE THREAD

**Issue by Eijin91** [titu1994/Image-Super-Resolution#14]
Good evening, i'm trying to train and test the CNN following the steps you mention in the readme file. 
I tried using some samples of mine, but i got some error. So i tried training the network using the dataset in your github. (i didn't modify anything in input_images or in validation images because i was just trying to understand how you trained the network).
I keep getting this error:

![errore1](https://user-images.githubusercontent.com/15212781/26891032-e05aaa5a-4bb3-11e7-9fac-ba576e3b8e8f.png)

Can you please help me solving this error? I don't know where to start.
Thanks in advance

**Comment by titu1994** [comment]
Hmm, it's a failed to allocate error so perhaps the image could not be loaded into GPU memory ?

Have you tried using smaller batch sizes ?

**Comment by Eijin91** [comment]
No i didn't, but i'll try that tomorrow. Thanks
