### ISSUE TITLE
 Input dimension mis-match. (input[1].shape[1] = 3, input[2].shape[1] = 64)

### ISSUE THREAD

**Issue by kankur** [titu1994/Image-Super-Resolution#15]
I have ran the code as python main.py input_images/t1.bmp
but got the error :
ValueError: Input dimension mis-match. (input[1].shape[1] = 3, input[2].shape[1] = 64)
Apply node that caused the error: Elemwise{Composite{(i0 * ((i1 + i2) + Abs((i1 + i2))))}}[(0, 1)](TensorConstant{(1, 1, 1, 1) of 0.5}, CorrMM{half, (1, 1), (1, 1)}.0, InplaceDimShuffle{x,0,x,x}.0)
Toposort index: 19
Inputs types: [TensorType(float32, (True, True, True, True)), TensorType(float32, 4D), TensorType(float32, (True, False, True, True))]
Inputs shapes: [(1, 1, 1, 1), (128, 3, 9, 8), (1, 64, 1, 1)]
Inputs strides: [(4, 4, 4, 4), (864, 288, 32, 4), (256, 4, 4, 4)]
Inputs values: [array([[[[ 0.5]]]], dtype=float32), 'not shown', 'not shown']
Outputs clients: [[CorrMM{half, (1, 1), (1, 1)}(Elemwise{Composite{(i0 * ((i1 + i2) + Abs((i1 + i2))))}}[(0, 1)].0, Subtensor{::, ::, ::int64, ::int64}.0), Elemwise{Composite{(i0 + (i1 * ((i2 + i3) + Abs((i2 + i3)))))}}[(0, 0)](Elemwise{Composite{(i0 * ((i1 + i2) + Abs((i1 + i2))))}}[(0, 1)].0, TensorConstant{(1, 1, 1, 1) of 0.5}, CorrMM_gradInputs{half, (1, 1), (1, 1)}.0, InplaceDimShuffle{x,0,x,x}.0)]]

**Comment by titu1994** [comment]
Please set image_data_format to channels_first
