### ISSUE TITLE
ImportError: cannot import name '__check_build'

### ISSUE THREAD

**Issue by ABDOELSHEMY** [titu1994/Image-Super-Resolution#20]
Hi @titu1994 
thank you for your great work in the progect, especially Supports Keras with Tensorflow backend, i failed to try your work befor because i never get Theano backend work in windows.
now when i try to upscal my own photo unfortunately i get this error.

python main.py G:\titu1994 Image-Super-Resolution\bank_lr.png
Using TensorFlow backend.
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import models
  File "G:\idm\titu1994 Image-Super-Resolution-master\models.py", line 12, in <module>
    import img_utils
  File "G:\idm\titu1994 Image-Super-Resolution-master\img_utils.py", line 5, in <module>
    from sklearn.feature_extraction.image import reconstruct_from_patches_2d, extract_patches_2d
  File "C:\Users\ABDO\AppData\Local\Programs\Python\Python35\lib\site-packages\sklearn\__init__.py", line 133, in <module>
    from . import __check_build
ImportError: cannot import name '__check_build'
how can i solve this please.

**Comment by titu1994** [comment]
Update your scikit-learn package to the latest version on pip. I think it's because of old package

**Comment by ABDOELSHEMY** [comment]
thank you for your quic replay
you are right i Update scikit-learn package and the error is gone, but i get new error 

Using TensorFlow backend.
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import models
  File "G:\idm\titu1994 Image-Super-Resolution-master\models.py", line 12, in <module>
    import img_utils
  File "G:\idm\titu1994 Image-Super-Resolution-master\img_utils.py", line 7, in <module>
    import cv
  File "C:\Users\ABDO\AppData\Local\Programs\Python\Python35\lib\site-packages\cv.py", line 1, in <module>
    from cv2.cv import *
ImportError: No module named 'cv2.cv'; 'cv2' is not a package.

i am using python 3.5, and opencv_python-3.3.0-cp35-cp35m-win_amd64.
sorry for wasting toyr time.

**Comment by titu1994** [comment]
It's fine. I really hate open cv dependency. In any case, try using conda install opencv after removing the pip install with pip uninstall opencv

**Comment by titu1994** [comment]
If this doesn't work, then remove the cv2 dependency and then remove the 3 lines which depend on it

**Comment by ABDOELSHEMY** [comment]
thank you very much for your help, i trying with conda but no luck
Using TensorFlow backend.
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import models
  File "G:\idm\titu1994 Image-Super-Resolution-master\models.py", line 12, in <module>
    import img_utils
  File "G:\idm\titu1994 Image-Super-Resolution-master\img_utils.py", line 7, in <module>
    import cv
ImportError: No module named 'cv'
PS G:\idm\titu1994 Image-Super-Resolution-master> python main.py G:\idm\titu1994 Image-Super-Resolution-master\bank_lr.p
ng
Using TensorFlow backend.
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import models
  File "G:\idm\titu1994 Image-Super-Resolution-master\models.py", line 12, in <module>
    import img_utils
  File "G:\idm\titu1994 Image-Super-Resolution-master\img_utils.py", line 7, in <module>
    import cv
ImportError: No module named 'cv'
so could you please explain in wich file exactly i should remove the cv2 dependency and then remove the 3 lines which depend on it, irealy want to use your progect along time ago, and i strongly hope i will chieve that after your new update,thank you.

**Comment by ABDOELSHEMY** [comment]
thank you so much for Improved support for opencv.

**Comment by titu1994** [comment]
Is it working now ? Its not possible to remove the support, since it boosts image quality, but its a pain to install on Windows

**Comment by ABDOELSHEMY** [comment]
Unfortunately  no, the same ImportError: No module named 'cv', i had most the day reading about this error but seem like its no dirct solve to it, but realy i want to thank you for your great helping and effort.

**Comment by titu1994** [comment]
Hmm I know it is unconventional, but if you are using pycharm, follow the error to the point where it is causing the trouble loading. 

If you see a line like import cv2.cv ... then remove the .cv part and see if it works.

**Comment by ABDOELSHEMY** [comment]
ok, i will try my best, and if any time i resolve this i definitely will let you know, thank you sir for this great helping, and sorry for all the time you spend to try to with this unique error.

**Comment by titu1994** [comment]
No problem. Open cv is really bad on Windows, but the quality of images is dependent on it sadly.

**Comment by ABDOELSHEMY** [comment]
Hi @titu1994 
1- first i uninstall anaconda and install python 3.5.4

2- i install opencv_python-3.3.1+contrib-cp35-cp35m-win_amd64.whl from [unofficial site ](http://www.lfd.uci.edu/~gohlke/pythonlibs/#opencv)

3- [Relative to these](https://stackoverflow.com/questions/39534496/importerror-no-module-named-cv2-cv) i try to change (from cv2.cv import *) to (from cv2 import *) in the cv.py file in python 3.5 site-packages folder , i do not sure is i am do is right or not because i am not  professional programmer (just love it),but fainally the code is runing without error, and i can upscal my own photo 2x now, but you definitely right when you warning that the quality of images is dependent on it, the out photo has edge ringing and artifacts.
i go to get some sleep now, then i will try my luck again,thanks you.
