### ISSUE TITLE
ValueError: input shapes: [9,9,3,64], [9,9,64,3].

### ISSUE THREAD

**Issue by Heidisnaps** [titu1994/Image-Super-Resolution#21]
$ python main.py "input2.jpg" --scale=2 --model="sr"

Using TensorFlow backend.
Old Size :  (445, 676, 3)
New Size : (890, 1352, 3)
Number of patches = 1187635, Patch Shape = (8, 8)
Saving intermediate image.
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 2 in both shapes must be equal, but are 3 and 64 for 'Assign' (op: 'Assign') with input shapes: [9,9,3,64], [9,9,64,3].

**Comment by AlexXiao95** [comment]
I encountered the same problem. Anyone know how to solve this?

**Comment by titu1994** [comment]
Hmm the patch mode must have not been correctly dealt with during the refactor to support Tensorflow. If someone can find the fix to this, do submit since I am busy with coursework right now.

**Comment by Heidisnaps** [comment]
@titu1994 @AlexXiao95 Thank you. I expect a quick patch.

**Comment by jordangierschendorf** [comment]
We encountered the same problem. We tried both patch and fast modes but It does not change anything.
We tried to look into the code but we do not really know where to look. 
@titu1994 Could you give us some advice to debug ? We will submit the code if we find a way to fix this.  

Thank you

**Comment by titu1994** [comment]
The original command that gives this issue is not giving me any problems locally. Just to make sure, you are all using Tensorflow backend with the "channels_last" data format, yes?

**Comment by jordangierschendorf** [comment]
Yes it is written "Using TensorFlow backend" in the console when we run the script and our keras.json file looks like this : 
{
    "floatx": "float32",
    "image_data_format": "channels_last",
    "epsilon": 1e-07,
    "backend": "tensorflow"
}
Is everything ok ?

**Comment by titu1994** [comment]
Yes it seems to be fine I don't understand. I generally use without patch mode, and it works with this setting.

**Comment by jordangierschendorf** [comment]
Ok, what version of tensorflow, keras and h5py are you using? 
Thank you for your help

**Comment by titu1994** [comment]
TF 1.5, Keras 2.1.3 last tested (currently 2.1.4), h5py latest pip install.

**Comment by jordangierschendorf** [comment]
We upgraded TensorFlow to 1.5.0 and keras to 2.1.3 but still have the same problem. Our version of h5py is 2.7.1 (lastest with pip install)
Is there another configuration that we have to check ?
Otherwise, where is the function that reshapes the data and generates this error ? We will try to have a look at it.

ValueError: Dimension 2 in both shapes must be equal, but are 3 and 64. Shapes are [9,9,3,64] and [9,9,64,3]. for 'Assign' (op: 'Assign') with input shapes: [9,9,3,64], [9,9,64,3].

**Comment by titu1994** [comment]
That 9,9,3,64 and 9,9,64,3 is referring to the kernel matrix for the first CNN. The issue is somewhere in the channel dim component. 

Can you try the other models that are there such as the ResNet SR and the Distilled ResNetSR? 

I think it's something to do with the weights of the old SRCNN models. It is not loading correctly since it was generated during Keras 1.0 era using theano. So maybe it is not being loaded correctly for Tensorflow backend.

**Comment by jordangierschendorf** [comment]
Ok thank you for the information. We tried all the models and still get the same error.
Are the weights updated on your repository ? We try to look at the code and will let you know if we find something.

**Comment by jordangierschendorf** [comment]
We think we found the solution. We changed the "image_data_format" from "channels_last" to "channels_first" in the keras.json file and it seems to be working with all the models now! 

We have another question, do you have weights for a scale factor of 1 ? We would like to denoise our image without changing the size. 

Thank you for your code !

**Comment by titu1994** [comment]
That's not really a great solution since Tensorflow performed best with channels last. Anyway, it's a temporary fix I guess. 

Those are simple de-noising autoencoders. I think the de-noising super resources model takes I'm am image and returns an image of the same size.

**Comment by jordangierschendorf** [comment]
What is the de-noising super resources model ? Is it the ddsr model ?

**Comment by titu1994** [comment]
Yes the ddsr

**Comment by jordangierschendorf** [comment]
We tried the ddsr model, but the ouput image is twice the size of the input image

**Comment by titu1994** [comment]
Ah. It seems I don't have de-noising models then.

**Comment by priyanshu2210** [comment]
@jordangierschendorf  please help me locate keras.json  file , I have downloaded the zip file and the contents doesn't have any file named keras.json . Thanking you in advance please help me solve the error

**Comment by titu1994** [comment]
.Keras is a hidden folder located inside C:Users/(your username)/. You will need to enable viewing hidden files to see it. Inside it is Keras.json

**Comment by priyanshu2210** [comment]
Thank you @titu1994 will look forward to collaboration.

**Comment by priyanshu2210** [comment]
@titu1994 whenever I am setting scale=3,4,5... other than 2 , following error comes, I wanted to know how I can create weight files
**OSError: Unable to open file (unable to open file: name = 'weights/Deep Denoise Weights 5X.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)**

**Comment by titu1994** [comment]
That's because there are pretrained weights only for scale 2. For others, you need to train yourself.
