### ISSUE TITLE
how can I get a model architecture image as yours?

### ISSUE THREAD

**Issue by applezhao** [titu1994/Image-Super-Resolution#29]
Sorry as this question might not be proper to be posted here. But I do really like ur images displaying model architecture. I might be asking a very stupid question as I'm really pretty new to machine learning. But would u pls tell me how how can I get a model architecture image as yours such as https://raw.githubusercontent.com/titu1994/ImageSuperResolution/master/architectures/SRCNN.png? Is it manually drawn or from any tool? Thx so much.

**Comment by titu1994** [comment]
Keras has a plotting library based on graphvis. Use `from keras.utils.vis_utils.plot_model` to supply a model and plot the diagram.
