### ISSUE TITLE
How to  acheives very high PSNR score 37.46 dB  for  DDSRCNN

### ISSUE THREAD

**Issue by chulaihunde** [titu1994/Image-Super-Resolution#3]
when i   train the DDSRCNN network, i  only  acheive near 32.~ dB validation PSNR value in the first 300  epochs on the 91 image  dataset , Can you tell us the specifics?

**Comment by titu1994** [comment]
That was a mistake in calculation of the PSNR metric. With the correct metric DDSRCNN gets just around 32.6 PSNR over 100 epochs. 

I haven't had time to update the docs.
