### ISSUE TITLE
Syntax Error in model.py

### ISSUE THREAD

**Issue by dascylla** [titu1994/Image-Super-Resolution#32]
I cloned the repo and wanted to run a test image. Thus I entered the following command

> python2.7 main.py "/Users/X/PNGs/test_image.png"

And received the following error message:

> Traceback (most recent call last):
>   File "main.py", line 1, in <module>
>     import models
>   File "./models.py", line 70
>     def create_model(self, height=32, width=32, channels=3, load_weights=False, batch_size=128) -> Model:
>                                                                                                 ^
> SyntaxError: invalid syntax

Whats the meaning here? Obviously the string "-> Model" is not part of a regular method definition...

**Comment by titu1994** [comment]
This is python 3 type declaration. Remove that part and it should work.
