### ISSUE TITLE
SyntaxError: invalid syntax in models.py

### ISSUE THREAD

**Issue by JianbinGG** [titu1994/Image-Super-Resolution#33]
Hi Titu,

I got an error when first downloading and runing the main.py, the error is below, where do I miss to setup?

Thanks!
Jianbin

------------
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import models
  File "/home/jianmin/DL/Super_resolution/Image-Super-Resolution/models.py", line 70
    def create_model(self, height=32, width=32, channels=3, load_weights=False, batch_size=128) -> Model:
                                                                                                ^
SyntaxError: invalid syntax

**Comment by titu1994** [comment]
It's due to the "-> Model" part, which is Python 3 syntax. Remove that. I gotta note that I'm removing support for Python 2.7 eventually.

**Comment by JianbinGG** [comment]
Thanks!
