### ISSUE TITLE
 module 'img_utils' has no attribute 'output_path'

### ISSUE THREAD

**Issue by jacedang** [titu1994/Image-Super-Resolution#46]
I ran the following command line: **python main.py D:\3rd_semester\low_res_img_test.jpg --model=dsr**
I already installed the module **img_utils**
However, it appeared an error said 'output_path' not found. Search on the internet and there's not solution.
Looking for help.
Thanks!

**Comment by BCurbs** [comment]
I have the same problem. Please help.

**Comment by BCurbs** [comment]
What was your resolution to the problem? I have been unable to fix it. @jacedang
